### PR TITLE
PDE_DATA() replaced by pde_data() in 5.17

### PR DESCRIPTION
**Pull request by zack-vii**
c.f. https://github.com/openzfs/zfs/issues/13004

currently does not work on ubuntu-20 kernel 5.15.0

### CODE REVIEW

**Comment by zack-vii** [comment]
since the function PDA_DATA was only renamed in 5.17. the original patch causes a problem on kernel 5.15

```
In file included from /var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:33:
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c: In function ‘hb_seq_show’:
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/acq-fiber-hba.h:53:22: error: implicit declaration of function ‘pde_data’ [-Werror=implicit-function-declaration]
   53 | #define PDE_DATA(in) pde_data(in)
      |                      ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:103:27: note: in expansion of macro ‘PDE_DATA’
  103 |  struct AFHBA_DEV *adev = PDE_DATA(file_inode(file));
      |                           ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/acq-fiber-hba.h:53:22: warning: initialization of ‘struct AFHBA_DEV *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   53 | #define PDE_DATA(in) pde_data(in)
      |                      ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:103:27: note: in expansion of macro ‘PDE_DATA’
  103 |  struct AFHBA_DEV *adev = PDE_DATA(file_inode(file));
      |                           ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c: In function ‘hbd_seq_show’:
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/acq-fiber-hba.h:53:22: warning: initialization of ‘struct AFHBA_DEV *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   53 | #define PDE_DATA(in) pde_data(in)
      |                      ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:121:27: note: in expansion of macro ‘PDE_DATA’
  121 |  struct AFHBA_DEV *adev = PDE_DATA(file_inode(file));
      |                           ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c: In function ‘ab_seq_show’:
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/acq-fiber-hba.h:53:22: warning: initialization of ‘struct AFHBA_DEV *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   53 | #define PDE_DATA(in) pde_data(in)
      |                      ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:137:27: note: in expansion of macro ‘PDE_DATA’
  137 |  struct AFHBA_DEV *adev = PDE_DATA(file_inode(file));
      |                           ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c: In function ‘job_proc_show’:
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/acq-fiber-hba.h:53:22: warning: initialization of ‘struct AFHBA_DEV *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   53 | #define PDE_DATA(in) pde_data(in)
      |                      ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:241:27: note: in expansion of macro ‘PDE_DATA’
  241 |  struct AFHBA_DEV *adev = PDE_DATA(file_inode(file));
      |                           ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c: In function ‘iommu_proc_show’:
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/acq-fiber-hba.h:53:22: warning: initialization of ‘struct AFHBA_DEV *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   53 | #define PDE_DATA(in) pde_data(in)
      |                      ^~~~~~~~
/var/lib/dkms/dtacq-afhba404/1.1.1-1/build/afs_procfs.c:303:34: note: in expansion of macro ‘PDE_DATA’
  303 |         struct AFHBA_DEV *adev = PDE_DATA(file_inode(file));
      |                                  ^~~~~~~~
cc1: some warnings being treated as errors
```
